import { Client, GatewayIntentBits } from 'discord.js';
import { config } from './config.js';
import { handleInteraction } from './events/interactionCreate.js';
import { registerReady } from './events/ready.js';
import { handleMessage } from './events/messageCreate.js';
import { registerGuildMemberAdd } from './events/guildMemberAdd.js';
import { handleButton } from './events/buttons.js';
import { handleReactionAdd, handleReactionRemove } from './events/reactionRoles.js';
import { handleMessageDelete } from './events/messageDelete.js';
import { handleMemberJoin } from './events/guildMemberJoin.js';
import { handleMemberLeave } from './events/guildMemberRemove.js';
import { logger } from './lib/logger.js';
import { disconnectDatabase } from './database/prisma.js';

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.DirectMessages] });
registerReady(client);
registerGuildMemberAdd(client);
client.on('interactionCreate', (interaction) => { void handleInteraction(interaction); void handleButton(interaction); });
client.on('messageCreate', handleMessage);
client.on('messageDelete', handleMessageDelete);
client.on('guildMemberAdd', handleMemberJoin);
client.on('guildMemberRemove', handleMemberLeave);
client.on('messageReactionAdd', handleReactionAdd);
client.on('messageReactionRemove', handleReactionRemove);
process.on('SIGINT', async () => { await disconnectDatabase(); client.destroy(); process.exit(0); });
process.on('SIGTERM', async () => { await disconnectDatabase(); client.destroy(); process.exit(0); });
process.on('unhandledRejection', reason => logger.error('Unhandled rejection', { reason }));
await client.login(config.token);
